/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DataTable: typeof import('./../src/components/DataTable/index.vue')['default']
    FollowMenu: typeof import('./../src/components/FollowMenu/index.vue')['default']
    FormDrawer: typeof import('./../src/components/FormDrawer/index.vue')['default']
    ImgInputer: typeof import('./../src/components/ImgUpload/ImgInputer/index.vue')['default']
    ImgUpload: typeof import('./../src/components/ImgUpload/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spin: typeof import('./../src/components/Spin/index.vue')['default']
    TagsView: typeof import('./../src/components/TagsView/index.vue')['default']
    Toast: typeof import('./../src/components/Toast/index.vue')['default']
  }
}
