export default {
  permissions: [],
  menus: [
    // TODO
    {
      text: '主页',
      icon: 'home',
      hidden: false,
      to: '/home',
      type: 'VIEW',
      resource: 'Home',
    },
    {
      text: '关于',
      icon: '',
      hidden: true,
      to: '/about',
      type: 'VIEW',
      resource: 'About',
    },
    {
      text: '项目管理',
      icon: 'apps',
      hidden: false,
      to: '/project',
      type: 'MENU',
      resource: '',
      children: [
        {
          text: '项目列表',
          hidden: false,
          to: '/project/list',
          type: 'VIEW',
          resource: 'project/ProjectList',
        },
      ],
    },
    {
      text: '门店管理',
      icon: 'store',
      hidden: false,
      to: '/shop',
      type: 'MENU',
      resource: '',
      children: [
        {
          text: '门店列表',
          hidden: false,
          to: '/shop/list',
          type: 'VIEW',
          resource: 'shop/ShopList',
        },
      ],
    },
    {
      text: '员工管理',
      icon: 'face',
      hidden: false,
      to: '/employee',
      type: 'MENU',
      resource: '',
      children: [
        {
          text: '员工列表',
          hidden: false,
          to: '/employee/list',
          type: 'VIEW',
          resource: 'employee/EmployeeList',
        },
      ],
    },
    {
      text: '异常',
      icon: 'error',
      hidden: true,
      to: '/exception',
      type: 'MENU',
      resource: '',
      children: [
        {
          text: '401',
          icon: '',
          hidden: false,
          to: '/exception/401',
          type: 'VIEW',
          resource: 'exception/401',
        },
        {
          text: '403',
          icon: '',
          hidden: false,
          to: '/exception/403',
          type: 'VIEW',
          resource: 'exception/403',
        },
        {
          text: '404',
          icon: '',
          hidden: false,
          to: '/exception/404',
          type: 'VIEW',
          resource: 'exception/404',
        },
        {
          text: '500',
          icon: '',
          hidden: false,
          to: '/exception/500',
          type: 'VIEW',
          resource: 'exception/500',
        },
      ],
    },
  ],
}
